export const blogPosts = [
  {
    id: '1',
    title: '10 Tips for First-Time Home Buyers in 2024',
    excerpt: 'Buying your first home? Here are essential tips to help you navigate the real estate market with confidence.',
    image: '/images/blog/buying-tips.webp',
    author: 'Sarah Johnson',
    date: 'Jan 15, 2024',
    readTime: '5 min read',
    category: 'Buying Tips',
  },
  {
    id: '2',
    title: 'The Future of Real Estate: AI and Virtual Tours',
    excerpt: 'Discover how technology is transforming the way we buy, sell, and rent properties in the digital age.',
    image: '/images/blog/future-tech.webp',
    author: 'Michael Chen',
    date: 'Jan 10, 2024',
    readTime: '4 min read',
    category: 'Technology',
  },
  {
    id: '3',
    title: 'Maximizing Your Property Value: Renovation Guide',
    excerpt: 'Learn which home improvements offer the best return on investment before selling your property.',
    image: '/images/blog/renovation.webp',
    author: 'Emily Rodriguez',
    date: 'Jan 5, 2024',
    readTime: '6 min read',
    category: 'Selling Tips',
  },
  {
    id: '4',
    title: 'Rental Market Trends: What Landlords Need to Know',
    excerpt: 'Stay ahead of the competition with these insights into the current rental market landscape.',
    image: '/images/blog/rental-trends.webp',
    author: 'David Kim',
    date: 'Dec 28, 2023',
    readTime: '4 min read',
    category: 'Rental',
  },
  {
    id: '5',
    title: 'Sustainable Living: Eco-Friendly Homes on the Rise',
    excerpt: 'Explore the growing demand for energy-efficient and environmentally conscious properties.',
    image: '/images/blog/eco-homes.webp',
    author: 'Lisa Thompson',
    date: 'Dec 20, 2023',
    readTime: '5 min read',
    category: 'Trends',
  },
  {
    id: '6',
    title: 'Negotiation Strategies for Real Estate Investors',
    excerpt: 'Master the art of negotiation with these proven techniques from industry experts.',
    image: '/images/blog/negotiation.webp',
    author: 'Robert Taylor',
    date: 'Dec 15, 2023',
    readTime: '7 min read',
    category: 'Investing',
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'John Anderson',
    role: 'Homeowner',
    company: 'First-Time Buyer',
    content: 'The team made my first home buying experience seamless and stress-free. They found exactly what I was looking for within my budget!',
    rating: 5,
   // avatar: '/images/avatars/john.webp',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    role: 'Property Investor',
    company: 'Garcia Investments',
    content: 'Exceptional service! I have purchased multiple properties through them and each transaction has been smooth and professional.',
    rating: 5,
  },
  {
    id: '3',
    name: 'David Williams',
    role: 'CEO',
    company: 'Williams Realty Group',
    content: 'The platform has revolutionized how we manage our properties. The automation features alone have saved us countless hours.',
    rating: 5,
  //  avatar: '/images/avatars/david.webp',
  },
  {
    id: '4',
    name: 'Sarah Miller',
    role: 'Property Manager',
    company: 'Miller Properties',
    content: 'Outstanding support and innovative solutions. Our efficiency has increased by 40% since switching to this platform.',
    rating: 4,
  },
  {
    id: '5',
    name: 'James Wilson',
    role: 'Real Estate Agent',
    company: 'Wilson Real Estate',
    content: 'The best real estate management system I have used. Intuitive, powerful, and constantly improving.',
    rating: 5,
  },
  {
    id: '6',
    name: 'Jennifer Lee',
    role: 'Home Seller',
    company: '',
    content: 'Sold my home in just 2 weeks! The marketing tools and agent support were incredible.',
    rating: 5,
  //  avatar: '/images/avatars/jennifer.webp',
  },
];